# -*- mode:python; coding:utf-8; -*-

import os

justThreadPro_home = os.environ['HOME'] + '/lib.Linux.x86_64/JustThreadPro'
cppEnvironment = Environment(
    tools=[ 'g++', 'gnulink'],
    CPPPATH=[justThreadPro_home + '/include'],
    CXXFLAGS=['-std=c++11'],
    LINKFLAGS=['-static'],
    LIBPATH=[justThreadPro_home + '/libs'],
    LIBS=['justthread', 'pthread', 'rt'],
    )
for item in Glob('*.cpp'):
    name, extension = os.path.splitext(item.name)
    cppEnvironment.Command('run_' + name, cppEnvironment.Program(item), './$SOURCE')
